name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix: &platform-matrix
        runtimeId: [win-x64, linux-x64, linux-arm64]
        include:
          - runtimeId: win-x64
            os: windows-latest

          - runtimeId: linux-x64
            os: ubuntu-latest
            #os: ubuntu-22.04

          - runtimeId: linux-arm64
            #os: ubuntu-24.04-arm
            os: ubuntu-22.04-arm

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET SDKs
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x

    - uses: jimver/cuda-toolkit@v0.2.35
      with:
        method: 'network'
        cuda: '12.6.2'
        sub-packages: '["nvcc", "cccl"]'
    
    - name: Verify CUDA Installation
      run: nvcc --version # Verify installation

    - name: Checkout MatX
      uses: actions/checkout@v6
      with:
        repository: NVIDIA/matx
        path: Native/MatX

    - name: Build MatX Native Library
      shell: bash
      run: |
        cd Native
        mkdir build
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release -j$(nproc)
        find build/

    - name: Build
      shell: bash
      run: |
        dotnet restore
        dotnet build -c Release --no-restore
